export const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';
export const WEBSOCKET_CONNECTION_ERROR = 'WEBSOCKET_CONNECTION_ERROR';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_HISTORY_RECEIVED = 'MESSAGE_HISTORY_RECEIVED';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
